name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install-dependencies:
    uses: ./.github/workflows/jobs/install-dependencies.yml

  lint:
    needs: install-dependencies
    uses: ./.github/workflows/jobs/lint.yml
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}

  build:
    needs: install-dependencies
    uses: ./.github/workflows/jobs/build.yml
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}

  test:
    needs: install-dependencies
    uses: ./.github/workflows/jobs/test.yml
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}

  e2e:
    needs: install-dependencies
    uses: ./.github/workflows/jobs/e2e.yml
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}
