name: ci
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: |
          supabase start
          sleep 10
          npx supabase status --output env > .env.local
          cat .env.local
          source .env.local
          echo "NEXT_PUBLIC_SUPABASE_URL=$API_URL" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY" >> $GITHUB_ENV
          echo "SUPABASE_URL=$API_URL" >> $GITHUB_ENV
          echo "SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY" >> $GITHUB_ENV
          echo "SUPABASE_INBUCKET_URL=$INBUCKET_URL" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run e2e tests
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ env.NEXT_PUBLIC_SUPABASE_URL}}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ env.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
          SUPABASE_URL: ${{ env.SUPABASE_URL}}
          SUPABASE_SERVICE_ROLE_KEY: ${{ env.SUPABASE_SERVICE_ROLE_KEY}}
          SUPABASE_INBUCKET_URL: ${{ env.SUPABASE_INBUCKET_URL}}
        run: |
          npm run test:e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.run_id }}
          path: playwright-report/
          retention-days: 30
